// Generated by ReScript, PLEASE EDIT WITH CARE

import Gun from "gun";
import * as Gun$1 from "gun";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import Express from "express";
import * as Process from "process";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Handler from "./build/handler";

var svelteHandler = Handler.handler;

var app = Express();

var p = Js_dict.get(Process.env, "PORT");

var port = p !== undefined ? Belt_Option.getWithDefault(Belt_Int.fromString(p), 8765) : 8765;

app.use(Gun$1.serve);

app.use(svelteHandler);

var server = app.listen(port, (function () {
        console.log("Server running on port " + String(port));
      }));

var gun = new Gun({
      web: server,
      file: "data"
    });

export {
  svelteHandler ,
  app ,
  port ,
  server ,
  gun ,
}
/* svelteHandler Not a pure module */
