// Generated by ReScript, PLEASE EDIT WITH CARE

import HamburgerMenuSvelte from "./HamburgerMenu.svelte";

function make(prim) {
  return HamburgerMenuSvelte(prim);
}

export { make };
/* ./HamburgerMenu.svelte Not a pure module */
