// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Svelte from "svelte";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Store from "svelte/store";
import * as Belt_SortArray from "rescript/lib/es6/belt_SortArray.js";
import * as $$Navigation from "$app/navigation";
import * as LocationService from "../services/LocationService.mjs";

function formatDate(timestamp) {
  return new Date(timestamp).toLocaleDateString();
}

function make() {
  var state = Store.writable({
        locations: [],
        isLoading: true
      });
  Svelte.onMount(function () {
        var locations = Belt_SortArray.stableSortBy(Belt_List.toArray(LocationService.getLocations()), (function (a, b) {
                return b.createdAt - a.createdAt | 0;
              }));
        state.set({
              locations: locations,
              isLoading: false
            });
      });
  var handleDelete = function (id) {
    if (!window.confirm("Are you sure you want to delete this location?")) {
      return ;
    }
    LocationService.removeLocation(id);
    var currentState = Store.get(state);
    var filteredLocations = currentState.locations.filter(function (loc) {
          return loc.id !== id;
        });
    state.set({
          locations: filteredLocations,
          isLoading: currentState.isLoading
        });
  };
  var goToLocation = function (id) {
    return $$Navigation.goto("/location/" + id);
  };
  return {
          state: state,
          handleDelete: handleDelete,
          goToLocation: goToLocation,
          formatDate: formatDate
        };
}

export {
  formatDate ,
  make ,
}
/* svelte Not a pure module */
