// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Store from "svelte/store";
import * as $$Navigation from "$app/navigation";
import * as LocationService from "../services/LocationService.mjs";

function generateGuid() {
  var timestamp = String(Date.now());
  var random = String(Js_math.random_int(0, 1000000));
  return timestamp + "-" + random;
}

function make() {
  var state = Store.writable({
        locationName: "",
        isSubmitting: false,
        error: ""
      });
  var handleSubmit = async function () {
    var currentState = Store.get(state);
    if (currentState.locationName.trim() === "") {
      state.set({
            locationName: currentState.locationName,
            isSubmitting: currentState.isSubmitting,
            error: "Please enter a location name"
          });
      return ;
    }
    state.set({
          locationName: currentState.locationName,
          isSubmitting: true,
          error: ""
        });
    try {
      var locationId = generateGuid();
      LocationService.addLocation(locationId, currentState.locationName);
      return await $$Navigation.goto("/location/" + locationId);
    }
    catch (exn){
      state.set({
            locationName: currentState.locationName,
            isSubmitting: false,
            error: "Failed to create location"
          });
      return ;
    }
  };
  return {
          state: state,
          handleSubmit: handleSubmit
        };
}

export {
  generateGuid ,
  make ,
}
/* svelte/store Not a pure module */
