// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Svelte from "svelte";
import * as Store from "svelte/store";
import * as NumberService from "../services/NumberService.mjs";

function make(locationId) {
  console.log("NumberManager.res locationId:", locationId);
  var numberStore = Store.writable(undefined);
  var reservedNumberStore = Store.writable(undefined);
  var takeNumberRef = {
    contents: undefined
  };
  var relinquishNumberRef = {
    contents: undefined
  };
  var convertState = function (state) {
    if (typeof state !== "object") {
      return ;
    } else {
      return state.currentNumber;
    }
  };
  var convertReservation = function (state) {
    if (typeof state !== "object") {
      return ;
    } else {
      return state.reservation;
    }
  };
  Svelte.onMount(function () {
        var match = NumberService.initNumberManager(locationId);
        var dispatch = match.dispatch;
        var numberStoreGun = match.state;
        takeNumberRef.contents = (function () {
            return dispatch("TakeNumber");
          });
        relinquishNumberRef.contents = (function () {
            return dispatch("RelinquishNumber");
          });
        var unsub1 = numberStoreGun.subscribe(function (n) {
              numberStore.set(convertState(n));
            });
        var unsub2 = numberStoreGun.subscribe(function (n) {
              reservedNumberStore.set(convertReservation(n));
            });
        return (function () {
                  unsub1();
                  unsub2();
                });
      });
  var handleTakeNumber = function () {
    console.log("handleTakeNumber called");
    var take = takeNumberRef.contents;
    if (take !== undefined) {
      console.log("Calling take()");
      take();
    } else {
      console.log("takeNumberRef is None");
    }
  };
  var handleRelinquishNumber = function () {
    var relinquish = relinquishNumberRef.contents;
    if (relinquish !== undefined) {
      reservedNumberStore.set(undefined);
      relinquish();
      return ;
    }
    
  };
  return {
          numberStore: numberStore,
          reservedNumberStore: reservedNumberStore,
          handleTakeNumber: handleTakeNumber,
          handleRelinquishNumber: handleRelinquishNumber
        };
}

var numberManagerComponent = make;

export {
  make ,
  numberManagerComponent ,
}
/* svelte Not a pure module */
