// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Svelte from "svelte";
import * as Store from "svelte/store";
import * as NumberService from "../services/NumberService.mjs";

function make(locationId) {
  console.log("NumberManager.res locationId:", locationId);
  var numberStore = Store.writable(0);
  var reservedNumberStore = Store.writable(undefined);
  var takeNumberRef = {
    contents: undefined
  };
  var relinquishNumberRef = {
    contents: undefined
  };
  Svelte.onMount(function () {
        var match = NumberService.initNumberManager(locationId);
        takeNumberRef.contents = match[1];
        relinquishNumberRef.contents = match[2];
        return match[0].subscribe(function (n) {
                    numberStore.set(n);
                  });
      });
  var handleTakeNumber = function () {
    var take = takeNumberRef.contents;
    if (take === undefined) {
      return ;
    }
    var currentNumber = Store.get(numberStore);
    reservedNumberStore.set(currentNumber);
    take();
  };
  var handleRelinquishNumber = function () {
    var relinquish = relinquishNumberRef.contents;
    if (relinquish !== undefined) {
      reservedNumberStore.set(undefined);
      return relinquish();
    }
    
  };
  return {
          numberStore: numberStore,
          reservedNumberStore: reservedNumberStore,
          handleTakeNumber: handleTakeNumber,
          handleRelinquishNumber: handleRelinquishNumber
        };
}

var numberManagerComponent = make;

export {
  make ,
  numberManagerComponent ,
}
/* svelte Not a pure module */
