// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Svelte from "svelte";
import * as Store from "svelte/store";
import * as NumberService from "../services/NumberService.mjs";

function make(locationId) {
  console.log("NumberManager.res locationId:", locationId);
  var numberStore = Store.writable(0);
  var reservedNumberStore = Store.writable(undefined);
  var takeNumberRef = {
    contents: undefined
  };
  var relinquishNumberRef = {
    contents: undefined
  };
  Svelte.onMount(function () {
        var match = NumberService.initNumberManager(locationId);
        takeNumberRef.contents = match[2];
        relinquishNumberRef.contents = match[3];
        var unsub1 = match[0].subscribe(function (n) {
              numberStore.set(n);
            });
        var unsub2 = match[1].subscribe(function (n) {
              reservedNumberStore.set(n);
            });
        return (function () {
                  unsub1();
                  unsub2();
                });
      });
  var handleTakeNumber = function () {
    console.log("handleTakeNumber called");
    var take = takeNumberRef.contents;
    if (take !== undefined) {
      console.log("Calling take()");
      return take();
    } else {
      console.log("takeNumberRef is None");
      return ;
    }
  };
  var handleRelinquishNumber = function () {
    var relinquish = relinquishNumberRef.contents;
    if (relinquish !== undefined) {
      reservedNumberStore.set(undefined);
      return relinquish();
    }
    
  };
  return {
          numberStore: numberStore,
          reservedNumberStore: reservedNumberStore,
          handleTakeNumber: handleTakeNumber,
          handleRelinquishNumber: handleRelinquishNumber
        };
}

var numberManagerComponent = make;

export {
  make ,
  numberManagerComponent ,
}
/* svelte Not a pure module */
