// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Svelte from "svelte";
import * as Store from "svelte/store";
import * as NumberManager from "../NumberManager.mjs";

function make() {
  var numberStore = Store.writable(0);
  var takeNumberRef = {
    contents: undefined
  };
  Svelte.onMount(function () {
        var match = NumberManager.initNumberManager();
        takeNumberRef.contents = match[1];
        return match[0].subscribe(function (n) {
                    numberStore.set(n);
                  });
      });
  var handleTakeNumber = function () {
    var take = takeNumberRef.contents;
    if (take !== undefined) {
      return take();
    }
    
  };
  return {
          numberStore: numberStore,
          handleTakeNumber: handleTakeNumber
        };
}

var numberManagerComponent = make;

export {
  make ,
  numberManagerComponent ,
}
/* svelte Not a pure module */
