// Generated by ReScript, PLEASE EDIT WITH CARE

import ReservedNumberSvelte from "./ReservedNumber.svelte";

function make(prim) {
  return ReservedNumberSvelte(prim);
}

export {
  make ,
}
/* ./ReservedNumber.svelte Not a pure module */
