// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";
import * as SeaService from "./services/SeaService.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var storageKey = "browser_id";

var keyPairKey = "key_pair";

function generateId() {
  var timestamp = String(Date.now());
  var random = String(Js_math.random_int(0, 1000000));
  return timestamp + "-" + random;
}

async function getKeyPair() {
  var keyPairString = localStorage.getItem(keyPairKey);
  if (keyPairString !== null) {
    try {
      return JSON.parse(keyPairString);
    }
    catch (exn){
      return await SeaService.generateKeyPair();
    }
  } else {
    var keyPair = await SeaService.generateKeyPair();
    var keyPairString$1 = Belt_Option.getWithDefault(JSON.stringify(keyPair), "{}");
    localStorage.setItem(keyPairKey, keyPairString$1);
    return keyPair;
  }
}

function get() {
  var id = localStorage.getItem(storageKey);
  if (id !== null) {
    return id;
  }
  var newId = generateId();
  localStorage.setItem(storageKey, newId);
  return newId;
}

export {
  storageKey ,
  keyPairKey ,
  generateId ,
  getKeyPair ,
  get ,
}
/* SeaService Not a pure module */
