// Generated by ReScript, PLEASE EDIT WITH CARE

import Gun from "gun";

var gun = new Gun({
      peers: ["http://localhost:8765/gun"]
    });

var numbers = gun.get("take-a-number");

export {
  gun ,
  numbers ,
}
/* gun Not a pure module */
