// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Db from "../Db.mjs";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as BrowserId from "../BrowserId.mjs";
import * as SeaService from "./SeaService.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as BrowserId$1 from "../BrowserId";
import * as Store from "svelte/store";

function getBrowserId(prim) {
  return BrowserId$1.get();
}

function initNumberManager(locationId) {
  var store = Store.writable("Loading");
  var browserId = BrowserId$1.get();
  if (Db.numbers === undefined) {
    return {
            state: store,
            dispatch: (function (param) {
                return Promise.resolve({
                            TAG: "Error",
                            _0: "DatabaseError"
                          });
              })
          };
  }
  var numbers = Caml_option.valFromOption(Db.numbers);
  numbers.get(locationId).get("reservations").get(browserId).once(async function (reservationValue) {
        var keyPair = await BrowserId.getKeyPair();
        var tmp;
        if (reservationValue == null) {
          tmp = Promise.resolve(undefined);
        } else {
          var verified = await SeaService.verifyData(reservationValue, keyPair.pub);
          tmp = Promise.resolve(!(verified == null) ? Belt_Option.map(Belt_Int.fromString(verified), (function (n) {
                        return n;
                      })) : undefined);
        }
        var existingReservation = await tmp;
        numbers.get(locationId).get("current").once(async function (value) {
              var current = Belt_Option.flatMap((value == null) ? undefined : Caml_option.some(value), Belt_Int.fromString);
              if (current !== undefined) {
                store.set({
                      TAG: "Ready",
                      currentNumber: current,
                      reservation: existingReservation
                    });
              } else {
                numbers.get(locationId).get("current").put("0");
                store.set({
                      TAG: "Ready",
                      currentNumber: 0,
                      reservation: existingReservation
                    });
              }
            });
      });
  numbers.get(locationId).get("current").on(function (value) {
        var state = Store.get(store);
        if (typeof state !== "object") {
          return ;
        }
        var current = Belt_Option.flatMap((value == null) ? undefined : Caml_option.some(value), Belt_Int.fromString);
        if (current !== undefined) {
          store.set({
                TAG: "Ready",
                currentNumber: current,
                reservation: state.reservation
              });
          return ;
        }
        
      });
  var dispatch = async function (action) {
    var match = Store.get(store);
    if (action !== "TakeNumber") {
      if (typeof match !== "object") {
        return {
                TAG: "Error",
                _0: "DatabaseError"
              };
      } else if (match.reservation !== undefined) {
        numbers.get(locationId).get("reservations").get(browserId).put("");
        store.set({
              TAG: "Ready",
              currentNumber: match.currentNumber,
              reservation: undefined
            });
        return {
                TAG: "Ok",
                _0: undefined
              };
      } else {
        return {
                TAG: "Error",
                _0: "NoNumberToRelinquish"
              };
      }
    }
    if (typeof match !== "object") {
      return {
              TAG: "Error",
              _0: "DatabaseError"
            };
    }
    var current = match.currentNumber;
    if (match.reservation !== undefined) {
      return {
              TAG: "Error",
              _0: "AlreadyHasNumber"
            };
    }
    var keyPair = await BrowserId.getKeyPair();
    var signedNumber = await SeaService.signData(String(current), keyPair.priv);
    if (signedNumber === "") {
      return {
              TAG: "Error",
              _0: "DatabaseError"
            };
    }
    var data = {};
    data["number"] = String(current);
    data["signature"] = signedNumber;
    var jsonData = JSON.stringify(data);
    var ref = numbers.get(locationId).get("current");
    var ref$1 = numbers.get(locationId).get("reservations").get(browserId);
    await Promise.all([
          Promise.resolve((ref.put(String(current + 1 | 0)), undefined)),
          Promise.resolve((ref$1.put(jsonData), undefined))
        ]);
    store.set({
          TAG: "Ready",
          currentNumber: current + 1 | 0,
          reservation: current
        });
    return {
            TAG: "Ok",
            _0: undefined
          };
  };
  return {
          state: store,
          dispatch: dispatch
        };
}

export {
  getBrowserId ,
  initNumberManager ,
}
/* Db Not a pure module */
