// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Db from "../db";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Store from "svelte/store";

var gun = Db.gun;

var numbers = Db.numbers;

var numberStore = Store.writable(0);

function initNumberManager() {
  numbers.get("current").on(function (number) {
        if (number !== undefined) {
          numberStore.set(Belt_Option.getWithDefault(Belt_Int.fromString(number), 0));
          return ;
        }
        
      });
  var takeNumber = function () {
    numbers.get("current").once(function (number) {
          if (number === undefined) {
            return ;
          }
          var nextNumber = Belt_Option.getWithDefault(Belt_Int.fromString(number), 0) + 1 | 0;
          numbers.get("current").put(String(nextNumber));
        });
  };
  return [
          numberStore,
          takeNumber
        ];
}

export {
  gun ,
  numbers ,
  numberStore ,
  initNumberManager ,
}
/* gun Not a pure module */
