// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sea from "gun/sea";

function generateKeyPair() {
  return Sea.pair();
}

function signData(data, privateKey) {
  return Sea.work(data, privateKey).then(function (signed) {
              if (signed == null) {
                return Promise.resolve("");
              } else {
                return Promise.resolve(signed);
              }
            });
}

function verifyData(signedData, publicKey) {
  return Sea.work(signedData, publicKey);
}

export {
  generateKeyPair ,
  signData ,
  verifyData ,
}
/* gun/sea Not a pure module */
